/*
 * Copyright (c) 2015 seleniumQuery authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.seleniumquery.by.csstree.selector;

import io.github.seleniumquery.by.locator.SQLocator;

public interface SQCssSelector {

    /**
     * Converts this selector into a locator.
     * @return The locator, having the best strategy to find elements based on this selector.
     */
    SQLocator toSQLocator();

    /**
     * Appends this selector's locator into a previously generated locator, which always represent
     * the leftmost part of the selector/expression, generated up to this point.
     * The csstree is traversed "in-order".
     *
     * @param leftLocator The locator generated by the leftmost part of the tree.
     * @return The leftLocator with this selector's behavior appended.
     */
    SQLocator toSQLocator(SQLocator leftLocator);

}